const GRID=5,CELL=64,GAP=6,PAD=10,MAX=6;
const U={sword:{n:'ดาบ',i:'⚔',hp:140,atk:48,cr:.12},spear:{n:'หอก',i:'⟶',hp:115,atk:40,cr:.1},gun:{n:'ปืน',i:'▰',hp:95,atk:34,cr:.15},bow:{n:'ธนู',i:'➶',hp:75,atk:56,cr:.2},cannon:{n:'ปืนใหญ่',i:'✹',hp:60,atk:30,cr:.08},axe:{n:'ขวาน',i:'🪓',hp:110,atk:30,cr:.12},priest:{n:'นักบวช',i:'✚',hp:90,atk:18,cr:.05}},ORDER=['sword','spear','gun','bow','cannon','axe','priest'];
const S={phase:'deploy',turn:'player',auto:false,busy:false,world:1,stage:1,pick:null,atk:null,boss:null,g:{player:[],bot:[]},v:{player:[],bot:[]}};
const grid=()=>Array.from({length:GRID},()=>Array(GRID).fill(null));S.g.player=grid();S.g.bot=grid();S.v.player=grid();S.v.bot=grid();
const $=x=>document.getElementById(x),wait=x=>new Promise(r=>setTimeout(r,x)),alive=s=>{let a=[],q=new Set;S.g[s].flat().forEach(u=>{if(u&&u.hp>0&&!q.has(u)){q.add(u);a.push(u)}});return a},pos=(s,u)=>{for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++)if(S.g[s][r][c]===u)return{r,c}},coord=(r,c)=>String.fromCharCode(65+c)+(r+1);
function log(x,c=''){let d=document.createElement('div');d.className=c;d.textContent=x;$('log').appendChild(d);$('log').scrollTop=1e9}function say(x){$('turnBox').textContent=x}function mk(t,b=false){let h=U[t].hp*(b?5:1);return{type:t,hp:h,max:h,gauge:0,boss:b,cells:b?[[0,2],[0,3],[1,2],[1,3]]:null}}
function targets(s,r,c,t){let g=S.g[s],rows=s==='bot'?[0,1,2,3,4]:[4,3,2,1,0];if(t==='bow')return[{r,c,k:1}];if(t==='axe'){let fr=rows.find(x=>g[x].some(u=>u&&u.hp>0));return fr==null?[]:[0,1,2,3,4].map(c=>({r:fr,c,k:1}))}if(t==='cannon')return[{r,c,k:.7},...[[1,0],[-1,0],[0,1],[0,-1]].map(([a,b])=>({r:r+a,c:c+b,k:.45}))];let line=rows.filter(x=>g[x][c]?.hp>0),k=t==='gun'?[1,.6,.3]:t==='spear'?[1,.5]:[1];return line.slice(0,k.length).map((r,i)=>({r,c,k:k[i]}))}
function calc(u,r,c,foe,ult=false){if(u.type==='priest')return[];let m=ult?1.3:1,a=U[u.type];return targets(foe,r,c,u.type).filter(h=>h.r>=0&&h.r<GRID&&h.c>=0&&h.c<GRID).map(h=>{let cr=Math.random()<a.cr,d=Math.max(1,Math.round(a.atk*h.k*(.85+Math.random()*.3)*m));if(cr)d=Math.round(d*1.5);return{...h,d,cr}})}
function addGauge(u,n){u.gauge=Math.min(100,u.gauge+n)}
async function hit(s,hs){for(let h of hs){let u=S.g[s][h.r][h.c];if(u?.boss)u=S.boss;if(!u||u.hp<=0)continue;u.hp=Math.max(0,u.hp-h.d);addGauge(u,8);sync(s,u);float(cellX(h.c),cellY(s,h.r),`${h.cr?'CRIT! ':''}-${h.d}`,h.cr?'#ff3333':'#fff',h.cr);burst(cellX(h.c),cellY(s,h.r),h.cr?[0xffffff,0xff3333,0xffd166]:[0xffffff,0xffd166],h.cr?18:9);log(`→ ${U[u.type].n} ${h.cr?'CRIT ':''}${h.d} dmg · HP ${u.hp}`,'dm');if(!u.hp){for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++)if(S.g[s][r][c]===u){destroy(s,r,c);S.g[s][r][c]=null}log(`💀 ${U[u.type].n} ถูกทำลาย!`,'ko')}await wait(80)}}
function sync(s,u){for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++)if(S.g[s][r][c]===u)update(s,r,c)}function heal(s,r,c,n){let u=S.g[s][r][c];if(!u)return;let old=u.hp;u.hp=Math.min(u.max,u.hp+n);update(s,r,c);float(cellX(c),cellY(s,r),`+${u.hp-old}`,'#4ade80');burst(cellX(c),cellY(s,r),[0x4ade80,0xffffff],12)}
async function ult(s,p,tr,tc){let u=S.g[s][p.r][p.c];if(!u||u.gauge<100)return;u.gauge=0;sound('ult');log(`✨ ${U[u.type].n} ใช้ท่าไม้ตาย!`,'hl');let foe=s==='player'?'bot':'player';if(u.type==='priest'){alive(s).forEach(x=>{let p=pos(s,x);heal(s,p.r,p.c,Math.round(x.max*.3))});burst(W/2,H/2,[0x4ade80,0xffffff,0xc084fc],35);return}let hs=[];if(u.type==='bow'){for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++)if(S.g[foe][r][c])hs.push(...calc(u,r,c,foe,true))}else hs=calc(u,tr,tc,foe,true);await hit(foe,hs)}
async function attack(s,p,tr,tc){if(S.busy)return;S.busy=true;let u=S.g[s][p.r][p.c];if(!u){S.busy=false;return}let foe=s==='player'?'bot':'player';if(u.type==='priest'){if(s==='player'&&S.g.player[tr][tc]&&S.g.player[tr][tc]!==u){heal('player',tr,tc,Math.round(u.max*.28));addGauge(u,18);S.busy=false;return finish(s)}if(s==='bot'){let a=alive('bot').filter(x=>x.hp<x.max).sort((a,b)=>a.hp/a.max-b.hp/b.max)[0];if(a){let q=pos('bot',a);heal('bot',q.r,q.c,Math.round(u.max*.28));addGauge(u,18);S.busy=false;return finish(s)}}}addGauge(u,12);if(u.gauge>=100&&(s==='bot'||S.auto)){await ult(s,p,tr,tc);S.busy=false;if(check())return;return finish(s)}let hs=calc(u,tr,tc,foe),v=S.v[s][p.r][p.c];if(v){let x=v.x,y=v.y;scene.tweens.add({targets:v,x:cellX(tc),y:cellY(foe,hs[0]?.r??tr),duration:160,yoyo:true});sound(u.type);await wait(100);scene.tweens.add({targets:v,x,y,duration:160})}await hit(foe,hs);addGauge(u,8);await wait(100);S.busy=false;if(check())return;finish(s)}
function finish(s){S.turn=s==='player'?'bot':'player';render();if(S.turn==='bot')ai('bot');else if(S.auto)ai('player');else say('🟢 เทิร์นของคุณ')}
function best(s){let foe=s==='player'?'bot':'player',o=[];for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++){let u=S.g[s][r][c];if(!u)continue;if(u.type==='priest'){let a=alive(s).filter(x=>x.hp<x.max).sort((a,b)=>a.hp/a.max-b.hp/b.max)[0];if(a){let p=pos(s,a);o.push({p:{r,c},tr:p.r,tc:p.c,score:90})}continue}for(let tr=0;tr<GRID;tr++)for(let tc=0;tc<GRID;tc++){let h=calc(u,tr,tc,foe);if(h.length)o.push({p:{r,c},tr,tc,score:h.reduce((a,x)=>a+x.d,0)+(u.gauge>=100?120:0)})}}return o.sort((a,b)=>b.score-a.score)[0]}
function ai(s){if(S.phase==='over')return;S.busy=true;say(s==='player'?'🤖 AUTO BATTLE — AI กำลังเล่น':'🤖 ศัตรูกำลังคิด...');setTimeout(()=>{S.busy=false;let m=best(s);if(m)attack(s,m.p,m.tr,m.tc)},s==='player'?320:600)}
function makeEnemies(){S.g.bot=grid();S.boss=null;if(S.stage===5){let b=mk('cannon',true);b.hp=b.max=U.cannon.hp*(2+S.world*.7);S.boss=b;for(let p of b.cells)S.g.bot[p[0]][p[1]]=b;bossView();['spear','axe','bow'].forEach((t,c)=>{S.g.bot[2][c]=mk(t);create('bot',2,c,S.g.bot[2][c])});log(`👑 BOSS WORLD ${S.world}-5 — ขนาด 2×2 + ลูกน้อง`,'ko')}else{let n=5+Math.min(2,S.world-1);for(let i=0;i<n;i++){let r=Math.floor(i/GRID),c=i%GRID,t=ORDER[(i+S.world+S.stage)%6];S.g.bot[r][c]=mk(t);create('bot',r,c,S.g.bot[r][c])}}}
function next(){if(S.stage<5)S.stage++;else{S.stage=1;S.world++}if(S.world>10){S.phase='over';say('🏆 CAMPAIGN COMPLETE — ผ่าน 10 WORLD!');return}S.phase='deploy';S.turn='player';S.g.player=grid();Object.values(S.v.player).flat().forEach(v=>v?.destroy());S.v.player=grid();$('btnStart').style.display='block';$('btnNext').style.display='none';makeEnemies();say(`WORLD ${S.world} · STAGE ${S.stage} — จัดทัพ`);render()}
function check(){let p=alive('player').length,b=alive('bot').length;if(p&&b)return false;if(!p){S.phase='over';say('💀 DEFEAT');$('btnReset').style.display='block';return true}S.phase='over';log(`🏆 ชนะ WORLD ${S.world}-${S.stage}!`,'hl');say('🏆 VICTORY — ไปด่านถัดไป');$('btnNext').style.display='block';return true}
const W=GRID*C+(GRID-1)*GAP+PAD*2,H=2*(GRID*C+(GRID-1)*GAP)+110;let scene;function cellX(c){return PAD+c*(C+GAP)+C/2}function cellY(s,r){return(s==='bot'?32:GRID*(C+GAP)+58)+r*(C+GAP)+C/2}
function tex(sc,k,t,s){let q=sc.textures.createCanvas(k,40,40),x=q.getContext();x.fillStyle=s==='player'?'#4da3ff':'#ff6b6b';x.fillRect(7,7,26,27);x.fillStyle='#f2c48d';x.fillRect(13,10,14,11);x.fillStyle='#151923';x.fillRect(11,29,18,7);x.fillStyle='#fff';if(t==='priest'){x.fillRect(18,3,4,30);x.fillRect(10,15,20,4)}else x.fillRect(29,19,8,3);q.refresh()}
function create(s,r,c,u){let q=scene.add.container(cellX(c),cellY(s,r)),sp=scene.add.image(0,0,`u_${u.type}_${s}`).setScale(1.45),hp=scene.add.text(0,-27,`${u.hp}`,{fontFamily:'monospace',fontSize:'11px',color:'#fff',stroke:'#000',strokeThickness:4}).setOrigin(.5),gb=scene.add.rectangle(-24,29,48,4,0xc084fc).setOrigin(0,.5),hb=scene.add.rectangle(-24,35,48,4,0x4ade80).setOrigin(0,.5);q.add([sp,hp,gb,hb]);q.hp=hp;q.gb=gb;q.hb=hb;S.v[s][r][c]=q}
function bossView(){for(let[r,c]of S.boss.cells){let q=scene.add.container(cellX(c),cellY('bot',r)),b=scene.add.rectangle(0,0,C*1.9,C*1.9,0x7f1d1d).setStrokeStyle(5,0xffd166),t=scene.add.text(0,0,'👑',{fontSize:'40px'}).setOrigin(.5),hp=scene.add.text(0,-47,`${S.boss.hp}`,{fontFamily:'monospace',fontSize:'14px',color:'#fff',stroke:'#000',strokeThickness:5}).setOrigin(.5);q.add([b,t,hp]);q.hp=hp;S.v.bot[r][c]=q}}
function update(s,r,c){let u=S.g[s][r][c],v=S.v[s][r][c];if(!u||!v)return;v.hp.setText(`${u.hp}`);if(!u.boss){v.hb.width=48*u.hp/u.max;v.gb.width=48*u.gauge/100}}
function destroy(s,r,c){S.v[s][r][c]?.destroy();S.v[s][r][c]=null}function burst(x,y,cs,n){for(let i=0;i<n;i++){let q=scene.add.rectangle(x,y,4,4,cs[i%cs.length]).setDepth(100);scene.tweens.add({targets:q,x:x+(Math.random()-.5)*80,y:y+(Math.random()-.5)*80,alpha:0,duration:330,onComplete:()=>q.destroy()})}}
function float(x,y,t,col,cr=false){let q=scene.add.text(x,y-8,t,{fontFamily:'monospace',fontSize:cr?'20px':'16px',color:col,stroke:'#000',strokeThickness:5}).setOrigin(.5).setDepth(110);scene.tweens.add({targets:q,y:y-52,alpha:0,duration:700,onComplete:()=>q.destroy()})}
function render(){renderPicker();for(let s of['player','bot'])for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++)S.g[s][r][c]&&update(s,r,c);$('cnt').textContent=alive('player').length;$('campaign').textContent=`WORLD ${S.world}/10 · STAGE ${S.stage}/5${S.stage===5?' · 👑 BOSS':''}`;$('btnAuto').style.display=S.phase==='battle'?'block':'none'}
function renderPicker(){$('picker').innerHTML=ORDER.map(t=>`<button data-t="${t}" class="${S.pick===t?'on':''}"><b>${U[t].i} ${U[t].n}</b><small>HP ${U[t].hp} · ATK ${U[t].atk} · ULT +30%${t==='priest'?' · ฮีลเพื่อน / ฮีลหมู่':''}</small></button>`).join('')}
$('picker').onclick=e=>{let b=e.target.closest('button');if(b&&S.phase==='deploy'){S.pick=S.pick===b.dataset.t?null:b.dataset.t;render()}};$('btnStart').onclick=()=>{S.phase='battle';S.turn='player';S.pick=null;$('btnStart').style.display='none';log(`════ ⚔️ WORLD ${S.world}-${S.stage} ════`,'hl');say('🟢 เทิร์นของคุณ');render()};$('btnAuto').onclick=()=>{S.auto=!S.auto;$('btnAuto').textContent=S.auto?'⏸ ปิดต่อสู้อัตโนมัติ':'🤖 ต่อสู้อัตโนมัติ';if(S.auto&&S.turn==='player')ai('player')};$('btnNext').onclick=next;$('btnReset').onclick=()=>location.reload();
function clickCell(s,r,c){if(S.busy||S.phase==='over')return;if(S.phase==='deploy'){if(s==='player'){if(S.g.player[r][c])S.pick=null,S.atk={r,c};else if(S.pick&&alive('player').length<MAX){S.g.player[r][c]=mk(S.pick);create('player',r,c,S.g.player[r][c])}render()}return}if(S.turn!=='player'||S.auto)return;if(s==='player'){let u=S.g.player[r][c];if(S.atk&&S.g.player[S.atk.r][S.atk.c]?.type==='priest'&&u&&u!==S.g.player[S.atk.r][S.atk.c])attack('player',S.atk,r,c);else if(u)S.atk={r,c}}else if(S.atk)attack('player',S.atk,r,c);render()}
const cfg={type:Phaser.AUTO,parent:'stage',width:W,height:H,backgroundColor:'#0d1322',pixelArt:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_HORIZONTALLY},scene:{create(){scene=this;for(let s of['player','bot'])for(let t of ORDER)tex(this,`u_${t}_${s}`,t,s);for(let s of['bot','player']){let y=s==='bot'?32:GRID*(C+GAP)+58;this.add.text(PAD,y-20,s==='bot'?'ENEMY ARMY':'YOUR ARMY',{fontFamily:'monospace',fontSize:'13px',color:s==='bot'?'#ff6b6b':'#4da3ff'});for(let r=0;r<GRID;r++)for(let c=0;c<GRID;c++){this.add.rectangle(cellX(c),cellY(s,r),C,C,0x202a40).setStrokeStyle(2,0x4b5875).setInteractive().on('pointerdown',()=>clickCell(s,r,c));this.add.text(cellX(c)-C/2+5,cellY(s,r)-C/2+4,coord(r,c),{fontFamily:'monospace',fontSize:'8px',color:'#65738e'})}}makeEnemies();log('👋 10 WORLD × 5 STAGE · STAGE 5 = BOSS 2×2','hl');log('✨ เกจ Ultimate 100% · โจมตี/โดนตีได้เกจ · Ultimate +30%');render()}}};new Phaser.Game(cfg);
function sound(k){try{let A=window.AudioContext||window.webkitAudioContext;if(!window.ac)window.ac=new A;let a=window.ac,o=a.createOscillator(),g=a.createGain(),f={sword:260,spear:340,gun:110,bow:520,cannon:70,axe:180,priest:620,ult:55}[k]||240;o.frequency.value=f;o.type=['gun','cannon'].includes(k)?'sawtooth':'square';g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.17)}catch(e){}}